name: chat_flutter
description: A Flutter plugin toolkit for displaying chat records. Supporting basic content display of images, files, voice, text, and videos.
version: 3.0.0
homepage: https://github.com/xiaorui-23/chat_flutter

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  photo_view: ^0.15.0
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
