name: chat_flutter
description: A Flutter plugin toolkit for displaying chat records. Supporting basic content display of images, files, voice, text, and videos.
version: 1.0.10
homepage: https://github.com/xiaorui-23/chat_flutter

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


